"""
Django settings for WeHappy project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os  # 新增：用于拼接媒体文件路径

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-14+u())((lgr4$8_k5mrn@-%2v4_1tbbsras5*nh*=e!k94flw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'user',
    'order',
    'school',
    'core',
    'game',
    'channels'
]
ASGI_APPLICATION = 'WeHappy.asgi.application'
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 跨域配置（增强：支持文件上传+携带Cookie）
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True  # 新增：允许跨域携带Cookie（登录认证用）
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']  # 新增：支持OPTIONS请求（文件上传预检）
CORS_ALLOW_HEADERS = ['*']  # 新增：允许所有请求头

ROOT_URLCONF = 'WeHappy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WeHappy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'playclub',
        'USER': 'root',
        'PASSWORD': 'cp425680',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

WX_APP_ID = "wx42a969eefddc54a7"
WX_APP_SECRET = "f4c543043f3342b817b23408960096c4"
# JWT 配置（生成登录token用）
JWT_SECRET_KEY = "8k9s7H2p5Q8z9L7m3X6v8B9n2M5c7V8b9N6m4S8d9F7g3H8j2K9l5P8o7I9u0Y"
JWT_EXPIRATION_DELTA = 86400 * 60  # token有效期60天

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = 'static/'

# 新增：媒体文件配置（用户头像上传专用）
MEDIA_URL = '/media/'  # 头像访问URL前缀，如：http://IP:8000/media/avatars/xxx.jpg
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 头像本地存储路径：项目根目录/media文件夹

# 新增：文件上传限制（防止超大文件）
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 最大5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 同上

# 新增：Session配置（支持跨域登录认证）
SESSION_COOKIE_SAMESITE = 'None'  # 允许跨域携带Session Cookie
SESSION_COOKIE_SECURE = False  # 开发环境关闭HTTPS要求（生产环境改为True）