# Generated by Django 6.0.1 on 2026-02-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增主键')),
                ('school_name', models.CharField(max_length=100, verbose_name='学校名称')),
                ('city', models.CharField(max_length=50, verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '学校列表',
                'verbose_name_plural': '学校列表',
                'db_table': 'school_list',
                'indexes': [models.Index(fields=['city'], name='idx_school_list_city'), models.Index(fields=['school_name'], name='idx_school_list_name')],
                'unique_together': {('school_name', 'city')},
            },
        ),
    ]
