# Generated by Django 6.0.1 on 2026-02-24 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='身份名称')),
                ('game_type', models.CharField(choices=[('WEREWOLF', '狼人杀'), ('AVALON', '阿瓦隆'), ('BLOOD', '血染钟楼')], max_length=20, verbose_name='游戏类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='身份描述')),
                ('camp', models.CharField(help_text='好人阵营/坏人阵营/中立等', max_length=20, verbose_name='阵营')),
            ],
            options={
                'verbose_name': '游戏身份',
                'verbose_name_plural': '游戏身份',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=20, unique=True, verbose_name='房间ID')),
                ('game_type', models.CharField(choices=[('WEREWOLF', '狼人杀'), ('AVALON', '阿瓦隆'), ('BLOOD', '血染钟楼')], max_length=20, verbose_name='游戏类型')),
                ('max_players', models.IntegerField(default=10, verbose_name='最大人数')),
                ('current_players', models.IntegerField(default=1, verbose_name='目前人数')),
                ('is_started', models.BooleanField(default=False, verbose_name='游戏是否开始')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '游戏房间',
                'verbose_name_plural': '游戏房间',
            },
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='WebSocket通道名')),
                ('is_ready', models.BooleanField(default=False, verbose_name='是否准备')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.identity', verbose_name='分配的身份')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room', verbose_name='房间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_players', to=settings.AUTH_USER_MODEL, verbose_name='玩家')),
            ],
            options={
                'verbose_name': '房间玩家',
                'verbose_name_plural': '房间玩家',
                'unique_together': {('room', 'user')},
            },
        ),
    ]
