# Generated by Django 6.0.1 on 2026-02-25 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomplayer',
            name='identity',
        ),
        migrations.AlterUniqueTogether(
            name='roomplayer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roomplayer',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomplayer',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': '房间', 'verbose_name_plural': '房间'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='current_players',
        ),
        migrations.RemoveField(
            model_name='room',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='max_players',
        ),
        migrations.AlterField(
            model_name='room',
            name='creator',
            field=models.CharField(max_length=100, verbose_name='创建者昵称'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='房间ID'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='用户ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户昵称')),
                ('identity_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='分配的身份')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room', verbose_name='所属房间')),
            ],
            options={
                'verbose_name': '玩家',
                'verbose_name_plural': '玩家',
                'unique_together': {('room', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='RoomIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_name', models.CharField(max_length=50, verbose_name='身份名称')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='身份数量')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='game.room', verbose_name='所属房间')),
            ],
            options={
                'verbose_name': '房间身份配置',
                'verbose_name_plural': '房间身份配置',
                'unique_together': {('room', 'identity_name')},
            },
        ),
        migrations.DeleteModel(
            name='Identity',
        ),
        migrations.DeleteModel(
            name='RoomPlayer',
        ),
    ]
