# Generated by Django 6.0.1 on 2026-02-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_roomplayer_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='房间名称'),
        ),
    ]
