# Generated by Django 6.0.1 on 2026-02-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='username',
            new_name='user_name',
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('room', 'user_name')},
        ),
        migrations.RemoveField(
            model_name='player',
            name='user_id',
        ),
    ]
