# Generated by Django 6.0.1 on 2026-02-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginInfo',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='用户昵称')),
                ('user_time', models.DateTimeField(auto_now_add=True, verbose_name='首次登录时间')),
                ('user_star', models.IntegerField(default=0, verbose_name='用户星级/积分')),
                ('user_password', models.CharField(max_length=100, verbose_name='账号密码')),
            ],
            options={
                'verbose_name': '用户登录信息',
                'verbose_name_plural': '用户登录信息',
                'db_table': 'user_login_info',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='用户昵称')),
                ('user_sex', models.IntegerField(blank=True, choices=[(0, '男'), (1, '女'), (None, '未知')], null=True, verbose_name='性别')),
                ('user_birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('user_school', models.CharField(blank=True, max_length=100, null=True, verbose_name='学校名称')),
                ('user_avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像URL')),
                ('user_wx_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信号')),
                ('user_phone_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='手机号')),
                ('user_introduction', models.CharField(blank=True, max_length=500, null=True, verbose_name='个人简介')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '个人资料',
                'verbose_name_plural': '个人资料',
                'db_table': 'user_profile',
                'indexes': [models.Index(fields=['user_school'], name='idx_user_profile_school')],
            },
        ),
    ]
