# Generated by Django 6.0.1 on 2026-02-18 19:17

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to=user.models.generate_avatar_filename, verbose_name='头像文件'),
        ),
    ]
