# Generated by Django 6.0.1 on 2026-02-15 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitOrder',
            fields=[
                ('order_id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='订单ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='发起人昵称')),
                ('user_avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='发起人头像')),
                ('order_introduction', models.CharField(max_length=1000, verbose_name='招募介绍')),
                ('max_num', models.IntegerField(verbose_name='招募最大人数')),
                ('current_num', models.IntegerField(default=1, verbose_name='当前人数')),
                ('order_time', models.CharField(max_length=50, verbose_name='招募时间')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='发布时间')),
                ('status', models.IntegerField(choices=[(0, '招募中'), (1, '已结束'), (2, '已取消')], default=1, verbose_name='订单状态')),
            ],
            options={
                'verbose_name': '招募信息',
                'verbose_name_plural': '招募信息',
                'db_table': 'recruit_order',
                'indexes': [models.Index(fields=['user_name'], name='idx_recruit_order_user_name'), models.Index(fields=['order_time'], name='idx_recruit_order_time'), models.Index(fields=['status'], name='idx_recruit_order_status')],
            },
        ),
        migrations.CreateModel(
            name='RecruitUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, verbose_name='订单ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='参与人昵称')),
                ('is_owner', models.IntegerField(default=0, verbose_name='是否发起人')),
                ('join_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
            options={
                'verbose_name': '招募用户',
                'verbose_name_plural': '招募用户',
                'db_table': 'recruit_user',
                'indexes': [models.Index(fields=['order_id'], name='idx_recruit_user_order_id'), models.Index(fields=['user_name'], name='idx_recruit_user_user_name')],
                'unique_together': {('order_id', 'user_name')},
            },
        ),
    ]
