# Generated by Django 6.0.1 on 2026-02-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitorder',
            name='user_avatar',
        ),
    ]
