# Generated by Django 6.0.1 on 2026-02-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_recruitorder_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitorder',
            name='star',
            field=models.IntegerField(default=0, verbose_name='热度'),
        ),
    ]
