# Generated by Django 6.0.1 on 2026-02-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_recruitorder_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitorder',
            name='order_time',
            field=models.DateField(max_length=50, verbose_name='招募时间'),
        ),
        migrations.AlterField(
            model_name='recruitorder',
            name='status',
            field=models.IntegerField(choices=[(0, '招募中'), (1, '招募结束'), (2, '已取消')], default=1, verbose_name='订单状态'),
        ),
    ]
