# Generated by Django 6.0.1 on 2026-02-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_recruitorder_order_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitorder',
            name='status',
            field=models.IntegerField(choices=[(0, '招募中'), (1, '招募结束'), (2, '已取消')], default=0, verbose_name='订单状态'),
        ),
    ]
