# Generated by Django 6.0.1 on 2026-02-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_recruitorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruituser',
            name='status',
            field=models.IntegerField(choices=[(0, '参与'), (1, '已退出')], default=0, verbose_name='订单状态'),
        ),
    ]
